### ISSUE TITLE
Bug: Jobs created by CronJob resources should now show up in reported results 

### ISSUE THREAD

**Issue by bryantbiggs** [clowdhaus/eksup#28]
### Expected Behaviour

When interrogating resources for upgrade readiness, the Job definitions created by CronJobs should be excluded from the results since their definition is covered already by the CronJob spec

### Current Behaviour

Currently, the Job specs created by CronJobs are reported in the findings in addition to the CronJob that defines them

![image](https://user-images.githubusercontent.com/10913471/221244574-b8952c5b-fd23-4111-b34b-06f254d6e93c.png)

### Code snippet

```sh
N/A
```

### Possible Solution

Filter out Jobs that have an `ownerReferences`

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2023-02-24T17:15:00Z"
  generation: 1
  labels:
    controller-uid: 079d519d-72ba-4a77-a0d7-bb134ea425b0
    job-name: bad-cron-27954315
  name: bad-cron-27954315
  namespace: cronjob
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: bad-cron
    uid: 1f1e67a0-198b-4cc1-961b-e2baff5f21b0

```

### Steps to Reproduce

N/A

### eksup version

latest

### Operating system

macOS x86_64

### Error output

```Text
N/A
```
